In [1]:
import torch

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [2]:
W = torch.zeros(1, requires_grad = True)  # 학습을 하겠다
b = torch.zeros(1, requires_grad = True)

optimizer = torch.optim.SGD([W,b], lr = 0.01)

In [4]:
nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):
    hypothesis = x_train * W + b
    loss = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()   # gradient를 0으로 초기화
    loss.backward()         # gradient 계산
    optimizer.step()        # gradient descent

In [6]:
print(W)
print(b)

tensor([1.9974], requires_grad=True)
tensor([0.0060], requires_grad=True)


In [5]:
x = torch.FloatTensor([4])
print(x * W + b)

tensor([7.9955], grad_fn=<AddBackward0>)
