In [1]:
import torch
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [2]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[2],t[-1])
print(t[2:4],t[3:-1])
print(t[:2],t[4:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(2.) tensor(6.)
tensor([2., 3.]) tensor([3., 4., 5.])
tensor([0., 1.]) tensor([4., 5., 6.])


In [3]:
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9,]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [4]:
print(t.dim())
print(t.size())
print(t.shape)
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([2., 5., 8.])
torch.Size([3])
tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


In [5]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1 + m2)

tensor([5., 5.])


In [6]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [7]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [8]:
print("Mul vs Matmul")
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print("Shape of matrix 1:",m1.shape)
print("Shape of matrix 2: {}".format(m2.shape))
print(m1.matmul(m2))  # 2 x 1

print(m1 * m2)  # 2 x 2
print(m1.mul(m2))  # 2 x 2

Mul vs Matmul
Shape of matrix 1: torch.Size([2, 2])
Shape of matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [9]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [10]:
t = torch.IntTensor([1,2])  # Can't use mean() on integers
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Int instead.


In [11]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [13]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [17]:
print(t.max())

tensor(4.)


In [18]:
print(t.max(dim = 0))   # Return two values : max and argmax
print("Max :",t.max(dim = 0)[0])
print("Argmax : {}".format(t.max(dim = 0)[1]))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max : tensor([3., 4.])
Argmax : tensor([1, 1])


In [19]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
