In [1]:
import torch
import numpy as np

t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [2]:
print(ft.view([-1,3]))   # reshape과 동일하다.
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [3]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [4]:
t = torch.FloatTensor([[0],[1],[2]])
print(t)
print(t.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [5]:
print(t.squeeze())
print(t.squeeze(dim = 0))
print(t.squeeze(dim = 1))
print(t.squeeze().shape)

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])
torch.Size([3])


In [6]:
t = torch.FloatTensor([0,1,2])
print(t.shape)

torch.Size([3])


In [7]:
print(t.unsqueeze(0))
print(t.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [8]:
print(t.view([-1,3]))
print(t.view([-1,3]).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [9]:
print(t.unsqueeze(1))
print(t.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
print(t.unsqueeze(-1))
print(t.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [13]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [14]:
bt = torch.ByteTensor([True, False, True, False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [15]:
print(bt.long())
print(bt.float())

tensor([1, 0, 1, 0])
tensor([1., 0., 1., 0.])


In [16]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y], dim = 0))  # Concatenate,  tensor의 size가 match 되어야한다.
print(torch.cat([x,y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [19]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [22]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z]).shape)
print(torch.stack([x,y,z],dim = 1))
print(torch.stack([x,y,z],dim = 1).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [23]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [24]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [25]:
print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))     # In-place Operation
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
