# Linear Algebra

In [1]:
import numpy as np

## Matrics and matrix multiplication

In [2]:
A = np.array([[1, 4, 5, 12],
              [-5,8, 9, 0],
              [-6,7,11,19]])
print(A)

[[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]


In [3]:
# row and column access
A[0], A[-1], A[:,0], A[:,-1], A[:2, :3]

(array([ 1,  4,  5, 12]),
 array([-6,  7, 11, 19]),
 array([ 1, -5, -6]),
 array([12,  0, 19]),
 array([[ 1,  4,  5],
        [-5,  8,  9]]))

In [4]:
# matrix multiplication
v1 = np.array([0, 1, 2])
v2 = np.array([1, 0, -1])
v3 = np.array([0, 1, 1])
v4 = np.array([1, 1, 1])
M = np.vstack([v1, v2, v3])
print(M)
print(M.dot(v4))    # dot multiplication
print(M.dot(v4.T))
print(v4.T.dot(M))
print(v4.dot(M))

[[ 0  1  2]
 [ 1  0 -1]
 [ 0  1  1]]
[3 0 2]
[3 0 2]
[1 2 2]
[1 2 2]


In [5]:
print(np.dot(M, v4), np.dot(M, v4.T))  # equivalent to the above
print(np.dot(v4, M), np.dot(v4.T, M))

[3 0 2] [3 0 2]
[1 2 2] [1 2 2]


In [6]:
v4, v4.T   # 1-d array

(array([1, 1, 1]), array([1, 1, 1]))

In [7]:
v4.reshape(-1,1), v4.reshape(1,-1)

(array([[1],
        [1],
        [1]]),
 array([[1, 1, 1]]))

In [8]:
v5 = v4.reshape(1,-1)
v5

array([[1, 1, 1]])

In [9]:
v5, v5.T     # 2-d array

(array([[1, 1, 1]]),
 array([[1],
        [1],
        [1]]))

In [10]:
v4.shape, v4.T.shape, v5.shape, v5.T.shape

((3,), (3,), (1, 3), (3, 1))

In [11]:
# element-wise multiplication
np.multiply(M, [1,2,3]), np.multiply(v4, v4), M * [1,2,3], v4 * v4

(array([[ 0,  2,  6],
        [ 1,  0, -3],
        [ 0,  2,  3]]),
 array([1, 1, 1]),
 array([[ 0,  2,  6],
        [ 1,  0, -3],
        [ 0,  2,  3]]),
 array([1, 1, 1]))

In [13]:
det = np.linalg.det(M)  # determinant
M_inv = np.linalg.inv(M)
M_inv, M_inv.dot(M), M.dot(M_inv)

(array([[ 1.,  1., -1.],
        [-1.,  0.,  2.],
        [ 1., -0., -1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

## Eigen values, Eigen vectors

In [14]:
# A.v = lambda.v
A = np.array([[0., 1.],
              [-2.,-3.]])
A

array([[ 0.,  1.],
       [-2., -3.]])

In [15]:
eigvals, eigvecs = np.linalg.eig(A)

In [16]:
eigvals, eigvecs

(array([-1., -2.]),
 array([[ 0.70710678, -0.4472136 ],
        [-0.70710678,  0.89442719]]))

In [17]:
eigvals[0]*eigvecs[:,0] , A.dot(eigvecs[:,0])

(array([-0.70710678,  0.70710678]), array([-0.70710678,  0.70710678]))

In [18]:
eigvals[1]*eigvecs[:,1] , A.dot(eigvecs[:,1])

(array([ 0.89442719, -1.78885438]), array([ 0.89442719, -1.78885438]))

## LU decomposition
- A: n x n matrix
- A = LU or PLU (more computationally stable)
- L: lower triangle matrix, U: upper triangle matrix

In [19]:
from scipy.linalg import lu

In [20]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
P, L, U = lu(A)

In [22]:
P, L, U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.14285714, 1.        , 0.        ],
        [0.57142857, 0.5       , 1.        ]]),
 array([[7.        , 8.        , 9.        ],
        [0.        , 0.85714286, 1.71428571],
        [0.        , 0.        , 0.        ]]))

In [23]:
B = L.dot(U)
B

array([[7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [24]:
P.dot(L).dot(U)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## QR decomposition
- A: any m x n matrix
- A = QR
- Q: m x m (orthonormal matrix), R: m x n (upper triangle matrix)


In [25]:
from  scipy.linalg import qr

In [26]:
A = np.array([[1,2],
              [3,4],
              [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
Q, R = qr(A, mode='full')  # 'full' returns q, r with dimension (m,m), (m,n)
Q.round(2), R.round(2)

(array([[-0.17,  0.9 ,  0.41],
        [-0.51,  0.28, -0.82],
        [-0.85, -0.35,  0.41]]),
 array([[-5.92, -7.44],
        [ 0.  ,  0.83],
        [ 0.  ,  0.  ]]))

In [28]:
# reconstruct 
Q.dot(R)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [29]:
# orthogonality check
(Q[:,0]*Q[:,1]).sum(), (Q[:,1]*Q[:,2]).sum(), (Q[:,0]*Q[:,2]).sum()

(5.551115123125783e-17, 0.0, 1.6653345369377348e-16)

In [30]:
# normality check
for i in range(3):
    vec = np.array(Q[:,i])
    print((vec**2).sum())
    

1.0
1.0
1.0000000000000002


## Eigen decomposition
- A = P D PT
- all n x n matrix

In [31]:
A = np.array([[6,2],
             [2,3]])
A

array([[6, 2],
       [2, 3]])

In [32]:
eigvals, eigvecs = np.linalg.eig(A)
eigvals, eigvecs

(array([7., 2.]),
 array([[ 0.89442719, -0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))

In [33]:
np.diag(eigvals)

array([[7., 0.],
       [0., 2.]])

In [34]:
# reconstruct
P = eigvecs
D = np.diag(eigvals)
P.dot(D).dot(P.T)

array([[6., 2.],
       [2., 3.]])

## SVD decomposition
- A = U S VT
- U, V: orthgonal matrics (UT=U-1, VT=V-1)
- D: diagonal (all 0 except the diagonals), not necessarily square
- columns of U: left-singular vectors of A
- columns of V: right-singular vectors of A
- values along the diagonal of D: singular values (square root of eigen values of A.AT)

In [37]:
A = np.array([[1,2],
              [3,4],
              [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
U, S, VT = np.linalg.svd(A, full_matrices=True)

In [39]:
S

array([9.52551809, 0.51430058])

In [42]:
Smat = np.diag(S)
Smat = np.vstack([Smat, [0,0]])

In [43]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [44]:
Smat

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [45]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [46]:
U.dot(Smat).dot(VT)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [47]:
eigvals, eigvecs = np.linalg.eig(A.dot(A.T))
np.sqrt(eigvals.round(2))

array([ 9.52575456,  0.50990195, -0.        ])

In [48]:
eigvecs, U

(array([[-0.2298477 , -0.88346102,  0.40824829],
        [-0.52474482, -0.24078249, -0.81649658],
        [-0.81964194,  0.40189603,  0.40824829]]),
 array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]))

In [54]:
eigvals, eigvecs = np.linalg.eig(A.T.dot(A))
np.sqrt(eigvals.round(2))

array([0.50990195, 9.52575456])

In [55]:
eigvecs, VT

(array([[-0.78489445, -0.61962948],
        [ 0.61962948, -0.78489445]]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))